#!/usr/bin/env bash

convert_media() {
    local file="$1"

    if [ "${file##*.}" == "mkv" ]; then
        if [ -e "${file%.*}.mp4" ]; then
            echo "Skipping '$(basename "$file")'"
            return
        fi

        local extension="mp4"
        local opts="-nostats -loglevel 0 -c:v copy -c:a copy -c:s mov_text -movflags +faststart"
    else
        if [ -e "${file%.*}.mp3" ]; then
            echo "Skipping '$(basename "$file")'"
            return
        fi

        local extension="mp3"
        local opts="-nostats -loglevel 0 -c:v copy -c:a libmp3lame -q:a 2"
    fi

    echo "Processing '$(basename "$file")'"

    if which docker > /dev/null; then
        local filepath=$(dirname "$file")
        local filename=$(basename "$file")

        docker run --rm -v="$filepath:/tmp/workdir" -w="/tmp/workdir" jrottenberg/ffmpeg -i "${filename}" $opts "${filename%.*}.mp4"
    elif which ffmpeg > /dev/null; then
        ffmpeg -i "${file}" $opts "${file%.*}.mp4"
    elif which avconv > /dev/null; then
        avconv -i "${file}" $opts "${file%.*}.mp4"
    else
        echo "Could not locate Docker, FFMpeg or AVConv"
        exit 1
    fi

    if [ "$?" -ne "0" ]; then
        echo "Failed to convert file '$file'"
        exit 1
    fi
}

MEDIA_PATH=${1:-.}

if [ ! -d "$MEDIA_PATH" ]; then
    echo "Directory '$MEDIA_PATH' does not exist"
    exit 1
fi

find "$MEDIA_PATH" \
    -type f \
    \( -iname "*.mkv" -o -iname "*.m4a" \) \
    -not -iwholename "*.AppleDouble*" \
    -not -iwholename "*._*" \
    | while read file; do convert_media "$file"; done
